apiVersion: v1
kind: Service
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.selector.name }}
      protocol: TCP
      name: {{ .Values.selector.name }}
  selector:
    app: {{ .Values.selector.name }}
